# -*- coding: utf-8 -*-
"""CSV2JSNOL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4Y-ZU0XWdYOWggh9K09brxxzoOC2Udo
"""

import pandas as pd
df = pd.read_csv("Validation Data GPT.csv")
df.head()

def convert_to_gpt35_format(dataset):
    fine_tuning_data = []
    for _, row in dataset.iterrows():
        json_system = '{"'+row['System']+'"}'
        json_response = '{"'+row['Output']+'"}'
        fine_tuning_data.append({
            "messages": [
                {"role": "system", "content": json_system},
                {"role": "user", "content": row['Input']},
                {"role": "assistant", "content": json_response}
            ]
        })
    return fine_tuning_data


dataset = pd.read_csv("/content/Validation Data GPT.csv")
converted_data = convert_to_gpt35_format(dataset)
converted_data[0]['messages']

import json

def write_to_jsonl(data, file_path):
    with open(file_path, 'w') as file:
        for entry in data:
            json.dump(entry, file)
            file.write('\n')

training_file_name = "converted_data.jsonl"

write_to_jsonl(converted_data, training_file_name)


